name: Geo Dizek
favicon: null
layout_spectrum: 0.51138
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffff00'
    - '#7f7f7f'
    - '#000000'
    - '#ff00ff'
    - '#00ff00'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
