name: Geo Dizek
favicon: null
layout_spectrum: 0.95698849321343
typography_spectrum: 0.6202085097320378
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120000'
    - '#ad0000'
    - '#006600'
    - '#d99c4f'
    - '#ffda8d'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
